name: Graphene VPN Sync

on:
  schedule:
    - cron: '0 */6 * * *' 
  workflow_dispatch: 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: pip install requests

      - name: Run Graphene Engine
        # Запускаем из корня, но указываем путь к файлу в папке source
        run: python source/main.py

      - name: Push Changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "GrapheneBot"
          git config --global user.email "bot@graphene.vpn"
          git add .
          git diff-index --quiet HEAD || git commit -m "🚀 Graphene VPN: Safe Update"
          git push https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }} HEAD:${{ github.ref }}
