name: Graphene VPN Sync

on:
  schedule:
    - cron: '*/45 * * * *' # Обновляем каждые 45 минут, как договаривались
  workflow_dispatch: 

permissions:
  contents: write # Даем боту права на пуш в репозиторий

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: pip install requests

      - name: Run Graphene Engine
        env:
          # ВАЖНО: Прокидываем секрет из настроек GitHub в скрипт
          PREMIUM_KEY: ${{ secrets.PREMIUM_KEY }}
        run: python source/main.py

      - name: Push Changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "GrapheneBot"
          git config --global user.email "bot@graphene.vpn"
          git add .
          # Проверяем изменения, чтобы не было ошибки при пустом коммите
          if [ -n "$(git status --porcelain)" ]; then
            git commit -m "🚀 Graphene VPN: Safe Update [$(date +'%H:%M')]"
            git push https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }} HEAD:${{ github.ref }}
          else
            echo "No changes to commit"
          fi
